{
  lib,
  pkgs,
  repoPath,
  ...
}:

let
  shellAliases = import ../scripts/shell-aliases.nix { inherit repoPath; };
  eshellAliasDefinitions = lib.mapAttrs (_name: command: "${command} $*") shellAliases;
  emacsEshellAliases = pkgs.writeText "sk-eshell-aliases.el" ''
    ;;; Generated by Home Manager from core/home/modules/scripts/shell-aliases.nix.
    (require 'json)
    (setq sk/generated-eshell-aliases
          (json-parse-string
           ${builtins.toJSON (builtins.toJSON eshellAliasDefinitions)}
           :object-type 'alist
           :array-type 'list))
  '';
  emacsPackage = pkgs.emacs-gtk;
  aspellWithEnglish = pkgs.aspellWithDicts (dicts: [ dicts.en ]);
  emacsTreeSitterGrammars = with pkgs.tree-sitter-grammars; {
    bash = tree-sitter-bash;
    c = tree-sitter-c;
    cpp = tree-sitter-cpp;
    css = tree-sitter-css;
    html = tree-sitter-html;
    javascript = tree-sitter-javascript;
    json = tree-sitter-json;
    lua = tree-sitter-lua;
    markdown = tree-sitter-markdown;
    markdown-inline = tree-sitter-markdown-inline;
    nix = tree-sitter-nix;
    org = tree-sitter-org;
    python = tree-sitter-python;
    rust = tree-sitter-rust;
    toml = tree-sitter-toml;
    tsx = tree-sitter-tsx;
    typescript = tree-sitter-typescript;
    yaml = tree-sitter-yaml;
  };
  emacsTreeSitterGrammarBundle = pkgs.runCommand "t480s-emacs-tree-sitter-grammars" { } (
    ''
      mkdir -p "$out/lib"
    ''
    + lib.concatStringsSep "\n" (
      lib.mapAttrsToList (language: grammar: ''
        ln -s ${grammar}/parser "$out/lib/libtree-sitter-${language}.so"
      '') emacsTreeSitterGrammars
    )
  );
  emacsTreeSitterGrammarPath = "${emacsTreeSitterGrammarBundle}/lib";
  emacsRuntime = with pkgs; [
    emacsPackage
    bashInteractive
    coreutils
    findutils
    perl
    cmake
    gnumake
    gcc
    libtool
    autoconf
    automake
    pkg-config
    git
    ledger
    ripgrep
    fd
    editorconfig-core-c
    tree-sitter
    sqlite
    gnutls
    imagemagick
    zstd
    unzip
    pandoc
    texliveSmall
    aspellWithEnglish
    harper
    nodejs
    typescript
    typescript-language-server
    prettier
    html-tidy
    stylelint
    jsbeautifier
    lua
    lua-language-server
    stylua
    basedpyright
    pipenv
    black
    ruff
    python3Packages.pyflakes
    python3Packages.pytest
    vscode-langservers-extracted
    yaml-language-server
    bash-language-server
    marksman
    rust-analyzer
    rustc
    cargo
    rustfmt
    clang-tools
    shellcheck
    shfmt
    nixd
    nixfmt
  ];
  emacsPath = lib.makeBinPath emacsRuntime;
  emacsShell = "${pkgs.fish}/bin/fish";
  emacsSync = pkgs.writeShellScriptBin "emacs-sync" ''
    set -euo pipefail
    export PATH="${emacsPath}:''${PATH-}"
    export SK_EMACS_SHELL="${emacsShell}"
    export SK_EMACS_TREE_SITTER_GRAMMAR_PATH="${emacsTreeSitterGrammarPath}"
    export SK_EMACS_ESHELL_ALIASES_FILE="${emacsEshellAliases}"

    ${emacsPackage}/bin/emacs --batch \
      -l "$HOME/.config/emacs/early-init.el" \
      -l "$HOME/.config/emacs/lisp/sk-package.el" \
      --eval '(package-refresh-contents)'

    ${emacsPackage}/bin/emacs --batch \
      -l "$HOME/.config/emacs/early-init.el" \
      -l "$HOME/.config/emacs/init.el" \
      --eval '(message "emacs packages loaded")'

    vterm_dir="$(find "$HOME/.cache/emacs/elpa" -maxdepth 1 -type d -name 'vterm-*' | sort | tail -n 1)"
    test -n "$vterm_dir" || { echo "emacs-sync: vterm package directory not found" >&2; exit 1; }
    cmake -S "$vterm_dir" -B "$vterm_dir/build" -DUSE_SYSTEM_LIBVTERM=Off
    cmake --build "$vterm_dir/build"
    test -f "$vterm_dir/vterm-module.so"

    ${emacsPackage}/bin/emacs --batch \
      -l "$HOME/.config/emacs/early-init.el" \
      -l "$HOME/.config/emacs/init.el" \
      --eval '(progn (require (quote vterm)) (message "emacs-sync complete"))'
  '';
in
{
  home = {
    packages = emacsRuntime ++ [ emacsSync ];

    sessionVariables = {
      SK_EMACS_SHELL = emacsShell;
      SK_EMACS_TREE_SITTER_GRAMMAR_PATH = emacsTreeSitterGrammarPath;
      SK_EMACS_ESHELL_ALIASES_FILE = emacsEshellAliases;
    };

    file.".cache/emacs/tree-sitter-grammars".source = emacsTreeSitterGrammarBundle;
  };
}
