;;; sk-theme.el --- Sky theme skeleton -*- lexical-binding: t; -*-

(defconst sk/theme-colors
  '((foreground . "#f0efeb")
    (foreground-alt . "#ccc4b4")
    (background . "#1a1d21")
    (background-alt . "#171a1e")
    (surface . "#22262b")
    (surface-strong . "#282c34")
    (border . "#3d424a")
    (border-active . "#b4c0c8")
    (accent . "#b4c0c8")
    (accent-alt . "#b4bcc4")
    (muted . "#676d77")
    (success . "#b5d6bd")
    (warning . "#f0c674")
    (danger . "#ff7f7f")
    (selection-foreground . "#1a1d21")
    (selection-background . "#b4c0c8")
    (string . "#9fcfc4")
    (function . "#8edbd6")
    (keyword . "#8fb8ff")
    (number . "#c9bda4")
    (type . "#b9c7e6")
    (builtin . "#9ccfd8")
    (variable . "#ffd7a8")
    (property . "#aebfd0")
    (operator . "#d5dde5")
    (punctuation . "#9fa7b2")
    (doc . "#8fb2a6")
    (preprocessor . "#d6a2a8")
    (comment . "#7f8a99")
    (black . "#22262b")
    (red . "#cdacac")
    (green . "#9fcfc4")
    (yellow . "#f0c674")
    (blue . "#8fb8ff")
    (magenta . "#b9c7e6")
    (cyan . "#8edbd6")
    (white . "#f0efeb"))
  "Static Sky Night color tokens.")

(defun sk/theme-color (name)
  "Return Sky color token NAME."
  (alist-get name sk/theme-colors))

(deftheme sky-night "Sky Night theme for the clean Emacs experiment.")

(defun sk/apply-theme-faces (&optional live)
  "Apply the static Sky theme faces.
When LIVE is non-nil, also apply the face specs to the live
user theme for the current session."
  (let ((bg (sk/theme-color 'background))
        (bg-dim (sk/theme-color 'background-alt))
        (surface (sk/theme-color 'surface))
        (surface-strong (sk/theme-color 'surface-strong))
        (fg (sk/theme-color 'foreground))
        (fg-alt (sk/theme-color 'foreground-alt))
        (muted (sk/theme-color 'muted))
        (border (sk/theme-color 'border))
        (accent (sk/theme-color 'accent))
        (accent-alt (sk/theme-color 'accent-alt))
        (string (sk/theme-color 'string))
        (function (sk/theme-color 'function))
        (keyword (sk/theme-color 'keyword))
        (variable (sk/theme-color 'variable))
        (property (sk/theme-color 'property))
        (number (sk/theme-color 'number))
        (type (sk/theme-color 'type))
        (builtin (sk/theme-color 'builtin))
        (operator (sk/theme-color 'operator))
        (punctuation (sk/theme-color 'punctuation))
        (doc (sk/theme-color 'doc))
        (comment (sk/theme-color 'comment))
        (preprocessor (sk/theme-color 'preprocessor))
        (success (sk/theme-color 'success))
        (warning (sk/theme-color 'warning))
        (danger (sk/theme-color 'danger))
        (black (sk/theme-color 'black))
        (red (sk/theme-color 'red))
        (green (sk/theme-color 'green))
        (yellow (sk/theme-color 'yellow))
        (blue (sk/theme-color 'blue))
        (magenta (sk/theme-color 'magenta))
        (cyan (sk/theme-color 'cyan))
        (white (sk/theme-color 'white)))
  (let ((faces
         (list
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,accent))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(hl-line ((t (:background ,surface))))
   `(region ((t (:background ,accent :foreground ,bg))))
   `(mode-line ((t (:background ,bg :foreground ,fg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-dim :foreground ,muted :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,fg :weight bold))))
   `(tab-line ((t (:background ,bg :foreground ,muted :box nil))))
   `(tab-line-tab ((t (:background ,surface :foreground ,fg-alt :box (:line-width (4 . 3) :color ,surface)))))
   `(tab-line-tab-current ((t (:background ,surface-strong :foreground ,fg :weight bold :box (:line-width (4 . 3) :color ,surface-strong)))))
   `(tab-line-tab-inactive ((t (:background ,bg-dim :foreground ,muted :box (:line-width (4 . 3) :color ,bg-dim)))))
   `(tab-line-highlight ((t (:background ,surface-strong :foreground ,fg))))
   `(tab-line-close-highlight ((t (:background ,surface-strong :foreground ,danger))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,doc))))
   `(font-lock-doc-markup-face ((t (:foreground ,keyword))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-function-name-face ((t (:foreground ,function))))
   `(font-lock-function-call-face ((t (:foreground ,function :weight medium))))
   `(font-lock-keyword-face ((t (:foreground ,keyword :weight bold))))
   `(font-lock-constant-face ((t (:foreground ,number))))
   `(font-lock-number-face ((t (:foreground ,number))))
   `(font-lock-type-face ((t (:foreground ,type))))
   `(font-lock-builtin-face ((t (:foreground ,builtin))))
   `(font-lock-variable-name-face ((t (:foreground ,variable :weight medium))))
   `(font-lock-variable-use-face ((t (:foreground ,variable :weight medium))))
   `(font-lock-property-name-face ((t (:foreground ,property :weight medium))))
   `(font-lock-property-use-face ((t (:foreground ,property :weight medium))))
   `(font-lock-operator-face ((t (:foreground ,operator))))
   `(font-lock-punctuation-face ((t (:foreground ,punctuation))))
   `(font-lock-bracket-face ((t (:foreground ,punctuation))))
   `(font-lock-delimiter-face ((t (:foreground ,punctuation))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,punctuation))))
   `(font-lock-escape-face ((t (:foreground ,preprocessor))))
   `(font-lock-regexp-face ((t (:foreground ,preprocessor))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,preprocessor))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,keyword))))
   `(font-lock-negation-char-face ((t (:foreground ,operator))))
   `(font-lock-preprocessor-face ((t (:foreground ,preprocessor))))
   `(font-lock-warning-face ((t (:foreground ,warning :weight bold))))
   `(nix-keyword-face ((t (:foreground ,keyword :weight bold))))
   `(nix-keyword-warning-face ((t (:foreground ,warning :weight bold))))
   `(nix-attribute-face ((t (:foreground ,property))))
   `(nix-builtin-face ((t (:foreground ,builtin))))
   `(nix-constant-face ((t (:foreground ,number))))
   `(nix-antiquote-face ((t (:foreground ,preprocessor))))
   `(nix-store-path-face ((t (:foreground ,string))))
   `(nix-store-path-realised-face ((t (:foreground ,string))))
   `(nix-store-path-unrealised-face ((t (:foreground ,muted))))
   `(org-block ((t (:background ,surface-strong :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,surface-strong :foreground ,muted))))
   `(org-block-end-line ((t (:background ,surface-strong :foreground ,muted))))
   `(org-checkbox ((t (:foreground ,accent :weight bold))))
   `(org-code ((t (:foreground ,accent-alt))))
   `(org-date ((t (:foreground ,accent :underline t))))
   `(org-document-info ((t (:foreground ,fg-alt))))
   `(org-document-title ((t (:foreground ,accent :weight bold :height 1.25))))
   `(org-done ((t (:foreground ,success :weight bold))))
   `(org-drawer ((t (:foreground ,muted))))
   `(org-headline-done ((t (:foreground ,muted :strike-through t))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-level-1 ((t (:foreground ,accent :weight bold :height 1.35))))
   `(org-level-2 ((t (:foreground ,function :weight bold :height 1.25))))
   `(org-level-3 ((t (:foreground ,type :weight bold :height 1.15))))
   `(org-level-4 ((t (:foreground ,keyword :weight bold :height 1.08))))
   `(org-level-5 ((t (:foreground ,builtin :weight bold))))
   `(org-level-6 ((t (:foreground ,number :weight bold))))
   `(org-level-7 ((t (:foreground ,preprocessor :weight bold))))
   `(org-level-8 ((t (:foreground ,property :weight bold))))
   `(org-link ((t (:foreground ,accent :underline t))))
   `(org-meta-line ((t (:foreground ,comment :slant italic))))
   `(org-priority ((t (:foreground ,warning :weight bold))))
   `(org-quote ((t (:background ,surface-strong :foreground ,fg-alt :slant italic))))
   `(org-special-keyword ((t (:foreground ,muted))))
   `(org-table ((t (:foreground ,accent-alt))))
   `(org-tag ((t (:foreground ,muted :weight medium))))
   `(org-todo ((t (:foreground ,danger :weight bold))))
   `(org-verbatim ((t (:foreground ,warning))))
   `(org-warning ((t (:foreground ,warning :weight bold))))
   `(eshell-prompt ((t (:foreground ,accent :weight bold))))
   `(sk/eshell-prompt-directory ((t (:foreground ,function))))
   `(sk/eshell-prompt-symbol ((t (:foreground ,accent :weight bold))))
   `(eshell-ls-archive ((t (:foreground ,warning :weight bold))))
   `(eshell-ls-backup ((t (:foreground ,muted))))
   `(eshell-ls-clutter ((t (:foreground ,muted))))
   `(eshell-ls-directory ((t (:foreground ,function :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,success))))
   `(eshell-ls-missing ((t (:foreground ,danger :weight bold))))
   `(eshell-ls-product ((t (:foreground ,fg-alt))))
   `(eshell-ls-readonly ((t (:foreground ,type))))
   `(eshell-ls-special ((t (:foreground ,accent :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,accent-alt :weight bold))))
   `(eshell-ls-unreadable ((t (:foreground ,muted))))
   `(ansi-color-black ((t (:foreground ,black :background ,black))))
   `(ansi-color-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-blue ((t (:foreground ,blue :background ,blue))))
   `(ansi-color-magenta ((t (:foreground ,magenta :background ,magenta))))
   `(ansi-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-white ((t (:foreground ,white :background ,white))))
   `(ansi-color-bright-black ((t (:foreground ,muted :background ,muted))))
   `(ansi-color-bright-red ((t (:foreground ,red :background ,red :weight bold))))
   `(ansi-color-bright-green ((t (:foreground ,green :background ,green :weight bold))))
   `(ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow :weight bold))))
   `(ansi-color-bright-blue ((t (:foreground ,blue :background ,blue :weight bold))))
   `(ansi-color-bright-magenta ((t (:foreground ,magenta :background ,magenta :weight bold))))
   `(ansi-color-bright-cyan ((t (:foreground ,cyan :background ,cyan :weight bold))))
   `(ansi-color-bright-white ((t (:foreground ,fg :background ,fg :weight bold))))
   `(term-color-black ((t (:foreground ,black :background ,black))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue ((t (:foreground ,blue :background ,blue))))
   `(term-color-magenta ((t (:foreground ,magenta :background ,magenta))))
   `(term-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-white ((t (:foreground ,white :background ,white))))
   `(vterm-color-black ((t (:foreground ,black :background ,black))))
   `(vterm-color-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(vterm-color-blue ((t (:foreground ,blue :background ,blue))))
   `(vterm-color-magenta ((t (:foreground ,magenta :background ,magenta))))
   `(vterm-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(vterm-color-white ((t (:foreground ,white :background ,white))))
   `(vterm-color-inverse-video ((t (:inverse-video t))))
   `(doom-modeline ((t (:background ,bg))))
   `(doom-modeline-bar ((t (:background ,accent))))
   `(doom-modeline-bar-inactive ((t (:background ,bg-dim))))
   `(doom-modeline-panel ((t (:background ,surface-strong :foreground ,fg))))
   `(doom-modeline-highlight ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-emphasis ((t (:foreground ,function :weight bold))))
   `(doom-modeline-buffer-path ((t (:foreground ,type))))
   `(doom-modeline-buffer-file ((t (:foreground ,function :weight bold))))
   `(doom-modeline-buffer-modified ((t (:foreground ,warning :weight bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,keyword :weight bold))))
   `(doom-modeline-buffer-minor-mode ((t (:foreground ,muted))))
   `(doom-modeline-project-name ((t (:foreground ,accent-alt :weight bold))))
   `(doom-modeline-project-parent-dir ((t (:foreground ,muted))))
   `(doom-modeline-project-dir ((t (:foreground ,type))))
   `(doom-modeline-project-root-dir ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-vcs-default ((t (:foreground ,success))))
   `(doom-modeline-host ((t (:foreground ,builtin))))
   `(doom-modeline-time ((t (:foreground ,number))))
   `(doom-modeline-compilation ((t (:foreground ,function :weight bold))))
   `(doom-modeline-lsp-running ((t (:foreground ,function))))
   `(doom-modeline-lsp-success ((t (:foreground ,success))))
   `(doom-modeline-lsp-warning ((t (:foreground ,warning))))
   `(doom-modeline-lsp-error ((t (:foreground ,danger :weight bold))))
   `(doom-modeline-repl-success ((t (:foreground ,success))))
   `(doom-modeline-repl-warning ((t (:foreground ,warning))))
   `(doom-modeline-evil-normal-state ((t (:foreground ,accent :weight bold))))
   `(doom-modeline-evil-insert-state ((t (:foreground ,success :weight bold))))
   `(doom-modeline-evil-visual-state ((t (:foreground ,warning :weight bold))))
   `(doom-modeline-evil-replace-state ((t (:foreground ,danger :weight bold))))
   `(doom-modeline-evil-motion-state ((t (:foreground ,accent-alt :weight bold))))
   `(doom-modeline-evil-emacs-state ((t (:foreground ,fg-alt :weight bold))))
   `(doom-modeline-evil-operator-state ((t (:foreground ,preprocessor :weight bold))))
   `(doom-modeline-evil-user-state ((t (:foreground ,builtin :weight bold))))
   `(doom-modeline-info ((t (:foreground ,success))))
   `(doom-modeline-warning ((t (:foreground ,warning))))
   `(doom-modeline-urgent ((t (:foreground ,danger))))
   `(doom-modeline-debug ((t (:foreground ,warning))))
   `(lsp-headerline-breadcrumb-separator-face ((t (:foreground ,muted :height 0.9))))
   `(lsp-headerline-breadcrumb-project-prefix-face ((t (:foreground ,accent :weight bold))))
   `(lsp-headerline-breadcrumb-unknown-project-prefix-face ((t (:foreground ,muted :weight bold))))
   `(lsp-headerline-breadcrumb-path-face ((t (:foreground ,type))))
   `(lsp-headerline-breadcrumb-path-error-face ((t (:foreground ,danger :underline (:style wave :color ,danger) :inherit lsp-headerline-breadcrumb-path-face))))
   `(lsp-headerline-breadcrumb-path-warning-face ((t (:foreground ,warning :underline (:style wave :color ,warning) :inherit lsp-headerline-breadcrumb-path-face))))
   `(lsp-headerline-breadcrumb-path-info-face ((t (:foreground ,success :underline (:style wave :color ,success) :inherit lsp-headerline-breadcrumb-path-face))))
   `(lsp-headerline-breadcrumb-path-hint-face ((t (:foreground ,builtin :underline (:style wave :color ,builtin) :inherit lsp-headerline-breadcrumb-path-face))))
   `(lsp-headerline-breadcrumb-symbols-face ((t (:foreground ,function :weight bold))))
   `(lsp-headerline-breadcrumb-symbols-error-face ((t (:foreground ,danger :underline (:style wave :color ,danger) :inherit lsp-headerline-breadcrumb-symbols-face))))
   `(lsp-headerline-breadcrumb-symbols-warning-face ((t (:foreground ,warning :underline (:style wave :color ,warning) :inherit lsp-headerline-breadcrumb-symbols-face))))
   `(lsp-headerline-breadcrumb-symbols-info-face ((t (:foreground ,success :underline (:style wave :color ,success) :inherit lsp-headerline-breadcrumb-symbols-face))))
   `(lsp-headerline-breadcrumb-symbols-hint-face ((t (:foreground ,builtin :underline (:style wave :color ,builtin) :inherit lsp-headerline-breadcrumb-symbols-face))))
   `(lsp-headerline-breadcrumb-deprecated-face ((t (:foreground ,muted :strike-through t :inherit lsp-headerline-breadcrumb-symbols-face))))
   `(nerd-icons-blue ((t (:foreground ,function))))
   `(nerd-icons-blue-alt ((t (:foreground ,accent))))
   `(nerd-icons-lblue ((t (:foreground ,function))))
   `(nerd-icons-dblue ((t (:foreground ,accent))))
   `(nerd-icons-cyan ((t (:foreground ,builtin))))
   `(nerd-icons-cyan-alt ((t (:foreground ,type))))
   `(nerd-icons-lcyan ((t (:foreground ,builtin))))
   `(nerd-icons-dcyan ((t (:foreground ,type))))
   `(nerd-icons-green ((t (:foreground ,success))))
   `(nerd-icons-lgreen ((t (:foreground ,string))))
   `(nerd-icons-dgreen ((t (:foreground ,success))))
   `(nerd-icons-yellow ((t (:foreground ,number))))
   `(nerd-icons-lyellow ((t (:foreground ,number))))
   `(nerd-icons-dyellow ((t (:foreground ,warning))))
   `(nerd-icons-orange ((t (:foreground ,preprocessor))))
   `(nerd-icons-lorange ((t (:foreground ,preprocessor))))
   `(nerd-icons-dorange ((t (:foreground ,warning))))
   `(nerd-icons-red ((t (:foreground ,danger))))
   `(nerd-icons-lred ((t (:foreground ,danger))))
   `(nerd-icons-dred ((t (:foreground ,warning))))
   `(nerd-icons-red-alt ((t (:foreground ,preprocessor))))
   `(nerd-icons-purple ((t (:foreground ,keyword))))
   `(nerd-icons-purple-alt ((t (:foreground ,accent-alt))))
   `(nerd-icons-lpurple ((t (:foreground ,keyword))))
   `(nerd-icons-dpurple ((t (:foreground ,accent-alt))))
   `(nerd-icons-maroon ((t (:foreground ,preprocessor))))
   `(nerd-icons-lmaroon ((t (:foreground ,preprocessor))))
   `(nerd-icons-dmaroon ((t (:foreground ,danger))))
   `(nerd-icons-pink ((t (:foreground ,keyword))))
   `(nerd-icons-lpink ((t (:foreground ,keyword))))
   `(nerd-icons-dpink ((t (:foreground ,preprocessor))))
   `(nerd-icons-silver ((t (:foreground ,fg-alt))))
   `(nerd-icons-lsilver ((t (:foreground ,fg))))
   `(nerd-icons-dsilver ((t (:foreground ,muted))))
   `(solaire-default-face ((t (:background ,surface :foreground ,fg))))
   `(solaire-hl-line-face ((t (:background ,surface-strong))))
   `(solaire-line-number-face ((t (:background ,surface :foreground ,muted))))
   `(solaire-org-hide-face ((t (:background ,surface :foreground ,surface))))
   `(solaire-mode-line-face ((t (:background ,bg :foreground ,fg))))
   `(solaire-mode-line-inactive-face ((t (:background ,bg-dim :foreground ,muted))))
   `(internal-border ((t (:background ,surface))))
   `(fringe ((t (:background ,bg))))
   `(window-divider ((t (:foreground ,bg :background ,bg))))
   `(window-divider-first-pixel ((t (:foreground ,bg :background ,bg))))
   `(window-divider-last-pixel ((t (:foreground ,bg :background ,bg))))
   `(vertical-border ((t (:foreground ,border)))))))
    (apply #'custom-theme-set-faces 'sky-night faces)
    (when live
      (apply #'custom-theme-set-faces 'user faces)))))

(sk/apply-theme-faces)

(provide-theme 'sky-night)

(defun sk/load-theme ()
  "Load the Sky Night theme."
  (interactive)
  (sk/apply-theme-faces t)
  (enable-theme 'sky-night))

(provide 'sk-theme)

;;; sk-theme.el ends here
